<a href="https://colab.research.google.com/github/AleksandraJuras2000/Kurs_Udemi_nn/blob/main/01_podstawy/02_analiza_sieci_czynniki_pierwsze.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
np.random.seed(42)

In [ ]:
X=np.array([1.4, 0.7])    # np. długość, waga
y_true=np.array([1.8])     # i  mamy tu cenę produktu

In [ ]:
def initialize_parameters(n_x, n_h, n_y):
    W1 = np.random.rand(n_h, n_x)
    W2 = np.random.rand(n_h, n_y)
    return W1, W2
# ta funkcja zwróci nam dwie macierze wag



def forward_propagation(X, W1, W2):
    H1 = np.dot(X, W1)  #przeliczenie warstwy ukrytej
    y_pred = np.dot(H1, W2)  # przeliczenie warstwy wyjściowej
    return H1, y_pred
# tutaj karmimy nasza siec bo mnozy wszystkie macierze (H1 to warstwa ukryta)



def calculate_error(y_pred, y_true):
    return y_pred - y_true



def predict(X, W1, W2):
    _, y_pred = forward_propagation(X, W1, W2)
    return y_pred[0]



def backpropagation(X, W1, W2, learning_rate, iters=1000, precision=0.0000001):

    H1, y_pred = forward_propagation(X, W1, W2)
    train_loss = []

    for i in range(iters):
        error = calculate_error(y_pred, y_true)
        W2 = W2 - learning_rate * error * H1.T
        W1 = W1 - learning_rate * error * np.dot(X.T, W2.T)

        y_pred = predict(X, W1, W2)
        print(f'Iter #{i}: y_pred {y_pred}: loss: {abs(calculate_error(y_pred, y_true[0]))}')
        train_loss.append(abs(calculate_error(y_pred, y_true[0])))

        if abs(error) < precision:
            break

    return W1, W2, train_loss

In [ ]:
def build_model():

    W1, W2 = initialize_parameters(2, 2, 1)   # tworzymy losowe wagi

    W1, W2, train_loss = backpropagation(X, W1, W2, 0.01)  # uczymy model

    model = {'W1': W1, 'W2': W2, 'train_loss': train_loss} # zapisujemy wagi

    return model

In [ ]:
model = build_model()

Iter #0: y_pred 0.5214837089619264: loss: 1.2785162910380736
Iter #1: y_pred 0.5565881929848598: loss: 1.24341180701514
Iter #2: y_pred 0.592164122621301: loss: 1.207835877378699
Iter #3: y_pred 0.6281196101956574: loss: 1.1718803898043426
Iter #4: y_pred 0.6643596649907321: loss: 1.1356403350092679
Iter #5: y_pred 0.7007873699431533: loss: 1.0992126300568468
Iter #6: y_pred 0.7373050404335387: loss: 1.0626949595664614
Iter #7: y_pred 0.7738153446041978: loss: 1.0261846553958023
Iter #8: y_pred 0.8102223662790249: loss: 0.9897776337209752
Iter #9: y_pred 0.8464325937440109: loss: 0.9535674062559891
Iter #10: y_pred 0.8823558202546593: loss: 0.9176441797453407
Iter #11: y_pred 0.9179059450388367: loss: 0.8820940549611633
Iter #12: y_pred 0.9530016666267126: loss: 0.8469983333732874
Iter #13: y_pred 0.9875670634336238: loss: 0.8124329365663763
Iter #14: y_pred 1.0215320595274657: loss: 0.7784679404725343
Iter #15: y_pred 1.0548327763256566: loss: 0.7451672236743434
Iter #16: y_pred 1.087

In [ ]:
loss = pd.DataFrame({'train_loss': model['train_loss']})
loss = loss.reset_index().rename(columns={'index': 'iters'})
loss['iters'] += 1
loss.head()

iters  train_loss
0      1    1.278516
1      2    1.243412
2      3    1.207836
3      4    1.171880
4      5    1.135640

In [ ]:
import plotly.graph_objects as go

fig = go.Figure(data=go.Scatter(x=loss['iters'], y=loss['train_loss'], mode='markers+lines'))
fig.show()

In [ ]:
predict(X, model['W1'], model['W2'])

1.7999999067073609

## FUNKCJE AKTYWACJI SA BARDZO WAŻNE W SIECIACH NEUROWOYCH:
## 1. Jeśli chcemy skupic sie na regresji używamy funkcji liniowych
## 2. Jeśli chcemy cos sklasyfikować (prawd poszcz. klasy) f. sigmoid!
## 3. Domyśłnie f. aktywacji jest f. liniowa - linear

Ćwiczenie dla siebie

In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd
import plotly.express as px
tf.__version__

'2.18.0'

In [ ]:
data = np.random.randn(1000, 150)
labels = np.random.randint(2, size=(1000, 1))

print(data.shape, labels.shape)

(1000, 150) (1000, 1)


In [ ]:
data[:3]

array([[ 0.89977167,  0.09490072, -0.51281966,  0.65839073,  1.17025778,
        -0.3293414 , -0.31664499, -1.62149694, -2.50939896, -1.35152212,
         1.0395334 , -0.25000069,  2.02690435,  1.26412993,  0.24763633,
         1.8201105 , -0.82714555,  0.38460437, -1.9840828 ,  0.8738591 ,
         0.96359151,  0.60767966,  1.65461617,  0.5092211 , -0.16632494,
         1.56099708,  1.95868924,  0.55532526, -0.83561617,  1.84841539,
        -0.68027544, -0.39098837,  0.3830419 ,  1.47111599, -0.31252101,
         0.86316516,  0.02685875,  1.57982951, -0.92342389, -0.55738239,
        -0.7268695 , -0.23734999,  0.65223866, -0.14390214, -0.38226796,
         2.57469273,  0.66732675, -0.46322935,  1.20064959,  0.30715221,
        -0.54497252, -0.14070121,  1.09933289, -0.23921997,  1.88737213,
        -0.11319391, -0.55404183,  1.02150204,  1.55778081,  1.00311459,
         1.13639732, -2.42160785,  0.83869016,  2.05828229,  0.50036403,
         0.06969877,  0.93755645,  1.33703632, -1.0

In [ ]:
labels[:10] # losowo przypisane klasy

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/20


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.5050 - loss: 0.7649 - val_accuracy: 0.5450 - val_loss: 0.7945
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5939 - loss: 0.6704 - val_accuracy: 0.5450 - val_loss: 0.7825
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6333 - loss: 0.6358 - val_accuracy: 0.5150 - val_loss: 0.7774
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6863 - loss: 0.5999 - val_accuracy: 0.5050 - val_loss: 0.7755
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7155 - loss: 0.5694 - val_accuracy: 0.5200 - val_loss: 0.7760
Epoch 6/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7373 - loss: 0.5411 - val_accuracy: 0.5300 - val_loss: 0.7799
Epoch 7/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7640 - loss: 0.5218 - val_accuracy: 0.5250 - val_loss: 0.7852
Epoch 8/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8299 - loss: 0.4720 - val_accuracy: 0.5500 - val_loss: 0.7902
Ep

In [ ]:
dir(history.history)

['__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__ror__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'clear',
 'copy',
 'fromkeys',
 'get',
 'items',
 'keys',
 'pop',
 'popitem',
 'setdefault',
 'update',
 'values']

test dla mnie

In [11]:
import pandas as pd
import numpy as np
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Flatten
from tensorflow.keras.datasets.mnist import load_data

In [22]:
(X_train, y_train), (X_test, y_test) = load_data()

In [23]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(60000, 28, 28) (60000,)
(10000, 28, 28) (10000,)


In [24]:
# standaryzacja danych
X_train = X_train / 255.
X_test = X_test / 255.

In [25]:
X_test[:3]  # trzy pierwsze wiersze   ,,, X_test[3:] oznacza, że pobierasz wszystkie wiersze od indeksu 3 do końca

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])

In [26]:
model = Sequential()
model.add(Flatten(input_shape=(28, 28)))  # ta wartstwa ma za zadanie wypłaszczyc input do wektoru 28*28
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.2))  # podajemy do tej wartstwy procent neuronów w warstwie które chcielibyśmy ominąc, korzystamy z tego gdy model ma duż szanse na przeuczenie
model.add(Dense(10, activation='softmax'))

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ flatten_2 (Flatten)                  │ (None, 784)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 128)                 │         100,480 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_2 (Dropout)                  │ (None, 128)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 10)                  │           1,290 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 101,770 (397.54 KB)

 Trainable params: 101,770 (397.54 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
from tensorflow.keras.utils import to_categorical
y_train = to_categorical(y_train, num_classes=10)
y_train

array([[[1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]],

       [[0., 1., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]],

       [[1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0.

In [30]:
np.unique(y_train)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [27]:
model.fit(X_train, y_train, epochs=10, validation_split=0.2, batch_size=32)

Epoch 1/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.8463 - loss: 0.5308 - val_accuracy: 0.9571 - val_loss: 0.1565
Epoch 2/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9502 - loss: 0.1679 - val_accuracy: 0.9665 - val_loss: 0.1167
Epoch 3/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9652 - loss: 0.1159 - val_accuracy: 0.9708 - val_loss: 0.0998
Epoch 4/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.9730 - loss: 0.0893 - val_accuracy: 0.9726 - val_loss: 0.0908
Epoch 5/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9762 - loss: 0.0802 - val_accuracy: 0.9750 - val_loss: 0.0847
Epoch 6/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9793 - loss: 0.0660 - val_accuracy: 0.9770 - val_loss: 0.0816
Epoch 7/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.9834 - loss: 0.0535 - val_accuracy: 0.9758 - val_loss: 0.0828
Epoch 8/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9839 - loss: 0.0527 

In [31]:
model.layers

[<Flatten name=flatten_2, built=True>,
 <Dense name=dense_4, built=True>,
 <Dropout name=dropout_2, built=True>,
 <Dense name=dense_5, built=True>]

In [33]:
model.inputs

[<KerasTensor shape=(None, 28, 28), dtype=float32, sparse=False, name=keras_tensor_22>]

In [34]:
model.outputs   # 10 tak naprawde oznacza liczbe klas

[<KerasTensor shape=(None, 10), dtype=float32, sparse=False, name=keras_tensor_32>]

In [35]:
model.get_config()

{'name': 'sequential_3',
 'trainable': True,
 'dtype': {'module': 'keras',
  'class_name': 'DTypePolicy',
  'config': {'name': 'float32'},
  'registered_name': None},
 'layers': [{'module': 'keras.layers',
   'class_name': 'InputLayer',
   'config': {'batch_shape': (None, 28, 28),
    'dtype': 'float32',
    'sparse': False,
    'name': 'input_layer_2'},
   'registered_name': None},
  {'module': 'keras.layers',
   'class_name': 'Flatten',
   'config': {'name': 'flatten_2',
    'trainable': True,
    'dtype': {'module': 'keras',
     'class_name': 'DTypePolicy',
     'config': {'name': 'float32'},
     'registered_name': None},
    'data_format': 'channels_last'},
   'registered_name': None,
   'build_config': {'input_shape': (None, 28, 28)}},
  {'module': 'keras.layers',
   'class_name': 'Dense',
   'config': {'name': 'dense_4',
    'trainable': True,
    'dtype': {'module': 'keras',
     'class_name': 'DTypePolicy',
     'config': {'name': 'float32'},
     'registered_name': None},
  

In [37]:
model.get_weights()

[array([[ 0.0140912 ,  0.07268339, -0.076086  , ..., -0.0022305 ,
          0.03065453, -0.01554029],
        [-0.02783644,  0.02474245, -0.01552618, ...,  0.08108059,
          0.0298747 ,  0.01638227],
        [-0.0742881 ,  0.0678762 ,  0.03148948, ..., -0.04985476,
          0.07828299, -0.03036622],
        ...,
        [-0.04237892, -0.00688968, -0.07784406, ..., -0.07389165,
         -0.05835407, -0.00855799],
        [-0.06285183,  0.03592762, -0.02292631, ...,  0.00739726,
         -0.04859579, -0.03209991],
        [ 0.01577087,  0.04973576, -0.00111949, ...,  0.05600948,
          0.00276218, -0.03005263]], dtype=float32),
 array([-1.80539057e-01, -1.27168735e-02, -1.60717264e-01,  1.08258940e-01,
        -1.17650849e-03,  1.66822255e-01,  5.81904538e-02, -1.39237791e-01,
        -1.80700481e-01, -5.30861467e-02, -4.97758575e-02, -3.56813520e-02,
         8.32683071e-02, -4.85319272e-03,  1.40254214e-01,  1.27777234e-01,
         1.62543684e-01,  1.14826985e-01,  8.37357342e

In [38]:
model.get_weights()[0].shape

(784, 128)

In [39]:
model.get_weights()[1].shape

(128,)

In [40]:
model.get_weights()[2].shape

(128, 10)

In [42]:
model.get_weights()[3].shape

(10,)

JSON

In [43]:
model_json = model.to_json()

import json
parsed = json.loads(model_json)
print(json.dumps(parsed, indent=4))

{
    "module": "keras",
    "class_name": "Sequential",
    "config": {
        "name": "sequential_3",
        "trainable": true,
        "dtype": {
            "module": "keras",
            "class_name": "DTypePolicy",
            "config": {
                "name": "float32"
            },
            "registered_name": null
        },
        "layers": [
            {
                "module": "keras.layers",
                "class_name": "InputLayer",
                "config": {
                    "batch_shape": [
                        null,
                        28,
                        28
                    ],
                    "dtype": "float32",
                    "sparse": false,
                    "name": "input_layer_2"
                },
                "registered_name": null
            },
            {
                "module": "keras.layers",
                "class_name": "Flatten",
                "config": {
                    "name": "flatten_2",
   

In [45]:
from tensorflow.keras.models import model_from_json

model2 = model_from_json(model_json)
model2.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ flatten_2 (Flatten)                  │ (None, 784)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 128)                 │         100,480 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_2 (Dropout)                  │ (None, 128)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 10)                  │           1,290 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 305,312 (1.16 MB)

 Trainable params: 101,770 (397.54 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 203,542 (795.09 KB)

## yaml

In [48]:
model_yaml = model.to_yaml()
print(model_yaml)

AttributeError: 'Sequential' object has no attribute 'to_yaml'

In [51]:
print(dir(model))

['__annotations__', '__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_add_trackable_child', '_add_variable_with_custom_getter', '_aggregate_additional_loss', '_allow_non_tensor_positional_args', '_api_export_path', '_api_export_symbol_id', '_assert_compile_called', '_assert_input_compatibility', '_assign_variable_values', '_auto_config', '_build_by_run_for_kwargs', '_build_by_run_for_single_pos_arg', '_build_shapes_dict', '_call_has_mask_arg', '_call_has_training_arg', '_call_signature', '_called', '_check_quantize_args', '_check_super_called', '_checkpoint_adapter', '_checkpoint_dependencies', '_clear_losses', '_compile_config', '_compile_loss', '_compile_metrics', '

In [53]:
dense_layer = model.layers[1]
dense_layer

<Dense name=dense_4, built=True>

In [55]:
dense_layer.input

<KerasTensor shape=(None, 784), dtype=float32, sparse=False, name=keras_tensor_24>

In [57]:
dense_layer.output.shape

(None, 128)

In [58]:
dense_layer.trainable  # jesli dana warstwa jest wskazana do uczenia sie lub nie

True

## Podstawowe rodzaje warstw
1. Dense - warstwa gęsto połączona, wynik operacji
2. Activation - stosuje funkcję aktywacji
3. Dropout - porzuca wskazaną część neuronów w warstwie
4. Flatten - wypłaszcza dane wejściowe
5. Input - warstwa wejściowa, parametr shape określa rozmiar danych wejściowych